/// <reference types="types-for-adobe/Photoshop/2015.5"/>

const character_ids = {
  AdjustmentLayer:      app.charIDToTypeID( 'AdjL' ),
  Adjustment:           app.charIDToTypeID( 'Adjs' ),
  Blue:                 app.charIDToTypeID( 'Bl  ' ),
  Black:                app.charIDToTypeID( 'Blck' ),
  Brightness:           app.charIDToTypeID( 'BrgC' ),
  Channel:              app.charIDToTypeID( 'Chnl' ),
  Color:                app.charIDToTypeID( 'Clr ' ),
  Colors:               app.charIDToTypeID( 'Clrs' ),
  Composite:            app.charIDToTypeID( 'Ordn' ),
  Curve:                app.charIDToTypeID( 'Crv ' ),
  Curves:               app.charIDToTypeID( 'Crvs' ),
  CurvesAdjustment:     app.charIDToTypeID( 'CrvA' ),
  Exchange:             app.charIDToTypeID( 'Exch' ),
  From:                 app.charIDToTypeID( 'From' ),
  Get:                  app.charIDToTypeID( 'getd' ),
  Green:                app.charIDToTypeID( 'Grn ' ),
  Gamma:                app.charIDToTypeID( 'Gmm ' ),
  Grayscale:            app.charIDToTypeID( 'Blck' ),
  Horizontal:           app.charIDToTypeID( 'Hrzn' ),
  HueSaturation:        app.charIDToTypeID( 'HStr' ),
  Input:                app.charIDToTypeID( 'Inpt' ),
  Invert:               app.charIDToTypeID( 'Invr' ),
  LAB:                  app.charIDToTypeID( 'Lght' ),
  Layer:                app.charIDToTypeID( 'Lyr ' ),
  Levels:               app.charIDToTypeID( 'Lvls' ),
  LevelsA:              app.charIDToTypeID( 'LvlA' ),
  Make:                 app.charIDToTypeID( 'Mk  ' ),
  Monotone:             app.charIDToTypeID( 'Mntn' ),
  Duotone:              app.charIDToTypeID( 'Dtn ' ),
  Tritone:              app.charIDToTypeID( 'Trtn' ),
  Quadtone:             app.charIDToTypeID( 'Qdtn' ),
  null:                 app.charIDToTypeID( 'null' ),
  Ordinal:              app.charIDToTypeID( 'Ordn' ),
  PaintbrushTool:       app.charIDToTypeID( 'PbTl' ),
  Point:                app.charIDToTypeID( 'Pnt ' ),
  Red:                  app.charIDToTypeID( 'Rd  ' ),
  Reset:                app.charIDToTypeID( 'Rset' ),
  Select:               app.charIDToTypeID( 'slct' ),
  Set:                  app.charIDToTypeID( 'setd' ),
  Target:               app.charIDToTypeID( 'Trgt' ),
  To:                   app.charIDToTypeID( 'T   ' ),
  Type:                 app.charIDToTypeID( 'Type' ),
  Using:                app.charIDToTypeID( 'Usng' ),
  Vertical:             app.charIDToTypeID( 'Vrtc' ),
  Property:             app.charIDToTypeID( 'Prpr' ),
  Document:             app.charIDToTypeID( 'Dcmn' ),
  Ijsx:                 app.charIDToTypeID( 'Ijsx' ),
  GEfk:                 app.charIDToTypeID( 'GEfk' ),
  GEft:                 app.charIDToTypeID( 'GEft' ),
  GEfc:                 app.charIDToTypeID( 'GEfc' ),
  AccentedEdges:        app.charIDToTypeID( 'AccE' ),
  Dcmn:                 app.charIDToTypeID( 'Dcmn' ),
  Ordn:                 app.charIDToTypeID( 'Ordn' ),
  Trgt:                 app.charIDToTypeID( 'Trgt' ),
  Visible:              app.charIDToTypeID( 'Vsbl' ),
  MakeVisible:          app.charIDToTypeID( 'MkVs' )
};

export { character_ids };
export default character_ids;